version: "3.7"

services:
  dmm:
    image: "hryk-production-dmm"
    container_name: "hryk-production-dmm"
    ports:
      - "8080:8080"
    restart: always
    working_dir: /usr/src/app/app
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 --log-level info main:app
    environment:
      APP_ENV: "production"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

  db:
    image: "hryk_mysql_dev"
    container_name: "hryk_mysql_dev"
    build:
      context: ./docker/mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./var/log/mysql:/var/log/mysql
    environment:
      - TZ=Asia/Tokyo
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=hryk_db
    env_file:
      - .env.development
#   migration:
#     image: "hryk_migration_dev"
#     container_name: "hryk_migration_dev"
#     build:
#       context: ./docker/migration
#     restart: always
#     tty: true
#     volumes:
#       - ./services/migration:/usr/src/app
#       - ./var/log/migration:/var/log/mysql
#     working_dir: /usr/src/app
#     env_file:
#       - .env.development
